### ISSUE TITLE
Missing overview of dependencies

### ISSUE THREAD

**Issue by waterwin** [jj1bdx/wspr-cui#1]
It would help the user to see the dependencies before running into make errors.
- gfortran
- maybe others not fulfilled on a clean Raspbian image
Thank you,
de Erwin

**Comment by jj1bdx** [comment]
Thanks, I'll add the explanation to the documentation in a later version.

**Comment by jj1bdx** [comment]
Added the explanation in https://github.com/jj1bdx/wspr-cui/commit/09539d8f009a7f59686e9a32124240b74d217afd. I will add more if needed. Also, refer to the WSJT-X source code for the required tools. Issue closed.
