### ISSUE TITLE
User error or other in python3 wspr-trx-event-loop.py

### ISSUE THREAD

**Issue by waterwin** [jj1bdx/wspr-cui#2]
~/wspr-cui/wspr-trx $ python3 wspr-trx-event-loop.py
Traceback (most recent call last):
  File "wspr-trx-event-loop.py", line 5, in <module>
    from apscheduler.schedulers.blocking import BlockingScheduler
ModuleNotFoundError: No module named 'apscheduler'

**Comment by jj1bdx** [comment]
This is a required python package.
https://apscheduler.readthedocs.io/en/3.x/

**Comment by jj1bdx** [comment]
Explanation added in https://github.com/jj1bdx/wspr-cui/commit/09539d8f009a7f59686e9a32124240b74d217afd. Issue closed.

**Comment by waterwin** [comment]
Thanks for all the quick and helpful answers,
de ErwinPE3ES / F4VTQ
    On Thursday, February 17, 2022, 05:01:52 AM GMT+1, Kenji Rikitake ***@***.***> wrote:  
 
 


Closed #2.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
