### ISSUE TITLE
Making .c2 files decodable (not the same as audible)

### ISSUE THREAD

**Issue by waterwin** [jj1bdx/wspr-cui#4]
Dear Kenji-san,

I take this opportunity to ask you a question on your interesting work on wsprd.

I would like to be able to recover a .wav file from a .c2 file my Red Pitaya FPGA is producing. For wspr or FT8 I can directly decode the .c2 file with wsprd or ft8d. But the FST4W decoder jt9 does not accept .c2 files, only .wav files.
Your information tells me you can make a .c2 file audible but not decodable.
Do you have a clue why it is not so far recovered that it can be decoded ?
Is that 'just' the 1500 Hz shift or is more at stake?

Thank you kindly for your reaction,
Erwin

**Comment by jj1bdx** [comment]
Hi Erwin:

I guess you're mentioning this: https://github.com/jj1bdx/wspr-cui/blob/72f4afff5dd2070ed73c1a21dc90d3a43379b2e9/README.md?plain=1#L59-L74

Upsampling from the sampling rate 375Hz to 12000Hz means x32 upsampling, which is not easy unless you have an accurate resampler. And you need to have an IQ (complex) signal resampler. I've never tried one yet, but building a high-precision resampler and shifting code using the building blocks such as [r8brain-free-src](https://github.com/avaneev/r8brain-free-src/tree/master) and [the FineTuner object in airspy-fmradion](https://github.com/jj1bdx/airspy-fmradion/blob/main/sfmbase/FineTuner.cpp) *might* make a decodable output signal (not tested).
