### ISSUE TITLE
Hard crack in wsprsimwav file

### ISSUE THREAD

**Issue by 0x657373656C6C** [jj1bdx/wspr-cui#5]
Hi!

There seems to be a hard crack in the .wav files generated by wsprsimwav just at the point that it transitions from silence to modulation (see image). Unfortunately this causes some splatter on my SDR so I was wondering what I can do, or can be done, to make this a little better?

I've tried with 0 db, -6db, -9db output and its mostly the same.

-- Essell

![image](https://github.com/jj1bdx/wspr-cui/assets/25435508/64739778-4445-4464-9b8f-55dc5bfd88ad)

**Comment by jj1bdx** [comment]
I guess the easiest way to solve this issue is to gradually increase the output level from zero to the necessary one during the first couple of milliseconds, as a modern CW transmitter does.

**Comment by jj1bdx** [comment]
@yourapiexpert 
I've added the fix (setting 20-millisecond fading-in/out time for the WSPR audio signal) to prevent the clicks to the main branch as https://github.com/jj1bdx/wspr-cui/commit/9236c0f32555eca648ae3e1858f23f580e332564.
Please check it out.

**Comment by jj1bdx** [comment]
Note for @jj1bdx: the raised-cosine fading time tests showed:

* 10ms: somewhat audible clicks still remained
* 50ms: too slow and overkill
* 20ms: looked good

**Comment by jj1bdx** [comment]
@yourapiexpert 
This issue has been fixed on https://github.com/jj1bdx/wspr-cui/releases/tag/20240214. Thanks for the report!
